language: java
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_SECRET_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
  region: "us-east-1"
  app: "ckd-tracker"
  env: "ckd-tracker-dev"
  bucket_name: "elasticbeanstalk-us-east-1-542141166723"