language: java
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  region: us-east-1
  app: ckd-tracker
  env: ckd-tracker-dev
  bucket_name: "elasticbeanstalk-us-east-1-542141166723"
  on:
    branch: master